# Generated by Django 5.1.6 on 2025-03-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0004_alter_contactinfo_email_alter_contactinfo_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoffer',
            name='image',
        ),
        migrations.AlterField(
            model_name='clients',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nazwa firmy/Imię klienta'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data wysłania'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='message',
            field=models.TextField(blank=True, verbose_name='Wiadomość'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='subject',
            field=models.CharField(blank=True, max_length=30, verbose_name='Temat'),
        ),
        migrations.AlterField(
            model_name='maininfoabout',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='maininfoabout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='maininfoabout',
            name='job_title',
            field=models.CharField(max_length=40, verbose_name='Stanowisko'),
        ),
        migrations.AlterField(
            model_name='maininfoabout',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='maininfoabout',
            name='office_adress',
            field=models.CharField(max_length=200, verbose_name='Adres biura'),
        ),
        migrations.AlterField(
            model_name='maininfoabout',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='maininfoabout',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nazwa'),
        ),
    ]
