# Generated by Django 5.1.6 on 2025-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "business_card",
            "0006_alter_clients_options_alter_contactinfo_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="message",
            field=models.TextField(verbose_name="Wiadomość"),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Imię"),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="subject",
            field=models.CharField(max_length=30, verbose_name="Temat"),
        ),
    ]
